<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <UseWindowsForms>true</UseWindowsForms>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FlaUI.UIA3" Version="5.0.0" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="pine_c.dll" />
      <Resource Include="pine_c.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Resource>
      <None Remove="6FB692AB.pnach" />
      <Resource Include="6FB692AB.pnach">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Resource>
    </ItemGroup>

</Project>
